#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
# Project Information
info:
  info:
    app:
      name: @project.name@
      description: @project.description@
      version: @project.version@
      encoding: @project.build.sourceEncoding@
      java:
        version: @java.version@
