---
- hosts: all
  #remote_user: smiguelnet
  #vars:
  #  - ansible_ssh_user: smiguelnet
  tasks:
    - name: Build sample app
      docker_image:
        name: "192.168.1.67:5000/smiguelnet/sample-app:latest"
        nocache: yes
        rm: yes
        force: yes
        state: build
    - name: Run image
      docker_container:
        image: "192.168.1.67:5000/smiguelnet/sample-app:latest"
        name: sample-app
        environment:
          URL_SERVER_CONSUL: "192.168.1.67"
        ports:
          - 8080:8080
        restart_policy: always
        state: started
